### ISSUE TITLE
Will this work be open-sourced in the near future?

### ISSUE THREAD

**Issue by Like2021** [gigo-team/bev_lane_det#1]

**Comment by sgzqc** [comment]
+1

**Comment by qinjian623** [comment]
As the authors, we agree on open-source. But we need to follow our company's IP protection process.

It should be soon, maybe in a month or two. And when it comes, you will be notified.

Thank you all.

**Comment by qinjian623** [comment]
Hi, all

We've released our code now.

Thank you.

**Comment by Like2021** [comment]
> Hi, all
> 
> We've released our code now.
> 
> Thank you.

Thanks for your reply.
