### ISSUE TITLE
how to get the vc_intrinsic and vc_extrinsics?

### ISSUE THREAD

**Issue by madezhi** [gigo-team/bev_lane_det#11]
In the papar, it just say 'which are derived from the mean value of the in/extrinsic
parameters of the training dataset'.
I want to use Virtual Camera on other dataset with new in/extrinsic parameters. And I can't find corresponding code in this project. I wonder if you can explain the specific calculation method  of the intrinsic parameters and extrinsic parameters of the Virtual Camera.

**Comment by qinjian623** [comment]
The simplest way is the mean value of every camera's.

You can design your own way based on the distribution of your dataset.

Thank you.

**Comment by FeiYull** [comment]
@madezhi 
Transorm the 'GT' from camera coordinate system  to ego coordinate system by Path1, and you will get  'new GT'

Path1: True camera      -------|
                                                        V
                                                      ego(new waymo of this paper)
                                                      ^
Path2: Virtual camera   -----|

**Comment by EnternalTwinkle** [comment]
@madezhi Can you share the source code? Thank you very much，1017094591@qq.com
