### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by ppbangKGT** [gigo-team/bev_lane_det#2]
Thanks for your great work! I wonder how fast your model detects the lane while inference. Can FPS be greater than 10?
By the way, looking forward to your code.

**Comment by qinjian623** [comment]
We've tested inference FPS.

On V100, FPS of our model with Resnet 34 backbone is 185FPS (complied by TensorRT).

**Comment by ppbangKGT** [comment]
> We've tested inference FPS.
> 
> On V100, FPS of our model with Resnet 34 backbone is 185FPS (complied by TensorRT).

Thanks for your reply and your nice work.
