### ISSUE TITLE
will you please release the pretrained model?

### ISSUE THREAD

**Issue by sgzqc** [gigo-team/bev_lane_det#6]

**Comment by Rex-LK** [comment]
+1

**Comment by rhwang1314** [comment]
Sorry, we lost our pretrained model, but we will release it soon. Using the code here, you can easily implement the indicators in the paper.

**Comment by umie0128** [comment]
@rhwang1314 
催一下

**Comment by miaoxiaoting** [comment]
+1

**Comment by miaoxiaoting** [comment]
if no ckpt, the results likes follow: have on meanings
{'f1_score': 0.0,
 'precision': 0.0,
 'recall': 0.0,
 'x_error_close': nan,
 'x_error_far': nan,
 'z_error_close': nan,
 'z_error_far': nan}

**Comment by qinjian623** [comment]
hi, all,

You're welcome to contribute your own pre-trained model. Our team's focus has shifted, and we are now analyzing some more interesting conclusions based on the techniques from this paper. 

Here are the third-party reproduction results feedback and our suggestions:
https://github.com/gigo-team/bev_lane_det/issues/10

Feel free to provide us with your opinions and suggestions.

Thanks.
